# seachspecsES.yaml for linked-swissbib
# search target ElasticSearch
# ###########




AllFields:
  UsedTypes:
    - bibliographicResource
    - document
  UsedIndex:
    - testsb
  query:
    bool:
      should:
        multi_match:
          type:
            - cross_fields #should be default
          operator:
            - and #should be default
          fields:
            - dct:title
            - rdau:publicationStatement
            - @type
            - dct:contributor.@id
            - rdau:noteOnResource
            - dct:bibliographicCitation
            - bibo:isbn13
            - bibo:isbn10
#        nested:
#          path:
#            - dc:contributor
#          query:
#            multi_match:
#              fields:
#                - dc:contributor.foaf:firstName
#                - dc:contributor.foaf:lastName
#              type:
#                - cross_fields #should be default
#              operator:
#                - and # should be default



Contributor:
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - @id
        type:
          - cross_fields #should be default
        operator:
          - and # should be default

Resources:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - dc:contributor.foaf:Person.@id
        type:
          - cross_fields #should be default
        operator:
          - and # should be default

Work:
  UsedTypes:
    - work
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - @id
        type:
          - cross_fields #should be default
        operator:
          - and # should be default