# seachspecsES.yaml for linked-swissbib
# search target ElasticSearch
# ###########

# author for id
AuthorForId:
  Multisearch:
    - BibliographicResourceForAuthor
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - @id
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

# AuthorByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# SubjectByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# bibliographicResource for Author
BibliographicResourceForAuthor:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - dct:contributor
      type:
        - cross_fields #should be default
      operator:
        - and # should be default


AutocompleteAuthor:
  Multisearch:
    - AutocompleteInstance
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - foaf:name
        - foaf:firstName
        - foaf:lastName
        - schema:alternateName
        #- rdfs:label
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

AutocompleteInstance:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - dct:title
        - dct:contributor
      type:
        - cross_fields #should be default
      operator:
        - and # should be default


AllFields:
  UsedTypes:
    - bibliographicResource
    - document
  UsedIndex:
    - testsb
  query:
    bool:
      should:
        multi_match:
          type:
            - cross_fields #should be default
          operator:
            - and #should be default
          fields:
            - dct:title
            - rdau:publicationStatement
            - @type
            - dct:contributor
            - rdau:noteOnResource
            - dct:bibliographicCitation
            - bibo:isbn13
            - bibo:isbn10
#        nested:
#          path:
#            - dc:contributor
#          query:
#            multi_match:
#              fields:
#                - dc:contributor.foaf:firstName
#                - dc:contributor.foaf:lastName
#              type:
#                - cross_fields #should be default
#              operator:
#                - and # should be default



Contributor:
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - @id
        type:
          - cross_fields #should be default
        operator:
          - and # should be default

Resources:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - dct:contributor
        type:
          - cross_fields #should be default
        operator:
          - and # should be default

Work:
  UsedTypes:
    - work
  UsedIndex:
    - testsb
  query:
    #todo think about a mechanism to reference already defined queries
#    nested:
#      path:
#        - dct:BibliographicResource.dc:contributor
#      query:
      multi_match:
        fields:
          - @id
        type:
          - cross_fields #should be default
        operator:
          - and # should be default
