# seachspecsES.yaml for linked-swissbib
# search target ElasticSearch
# ###########

# author for id
AuthorForId:
  Multisearch:
    - BibliographicResourceForAuthor
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - @id
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

# subject by id
SubjectById:
  Multisearch:
    - BibliographicResourceForSubject
  UsedTypes:
    - DEFAULT
  UsedIndex:
    - gnd
  query:
    multi_match:
      fields:
        - @id
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

# AuthorByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# SubjectByIdMulti : see /usr/local/vufind/httpd/module/LinkedSwissbib/src/LinkedSwissbib/Backend/Elasticsearch/ESQueryBuilder.php

# bibliographicResource for Author
BibliographicResourceForAuthor:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - dct:contributor
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

# bibliographicResource for Subject
BibliographicResourceForSubject:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - dct:subject
      type:
        - cross_fields #should be default
      operator:
        - and # should be default


AutocompleteAuthor:
  Multisearch:
    - AutocompleteInstance
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - foaf:name
        - foaf:firstName
        - foaf:lastName
        - dbp:pseudonym.de
        - dbp:pseudonym.en
        - dbp:pseudonym.fr
        - dbp:pseudonym.it
        - schema:alternateName
        #- rdfs:label
      type:
        - cross_fields #should be default
      operator:
        - or # should be default

AutocompleteInstance:
  Multisearch:
    - AutocompleteSubject
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - dct:title
        - dct:contributor
      type:
        - cross_fields #should be default
      operator:
        - and # should be default

AutocompleteSubject:
  UsedTypes:
    - DEFAULT
  UsedIndex:
    - gnd
  query:
    multi_match:
      fields:
        #- http://d-nb_info/standards/elementset/gnd#preferredNameForTheConferenceOrEvent.@value
        - http://d-nb_info/standards/elementset/gnd#preferredNameForTheSubjectHeading.@value
        - http://d-nb_info/standards/elementset/gnd#variantNameForTheSubjectHeading.@value
        - @type
      type:
        - cross_fields
      operator:
        - and

AllFields:
  UsedTypes:
    - bibliographicResource
  UsedIndex:
    - testsb
  query:
    bool:
      should:
        multi_match:
          type:
            - cross_fields #should be default
          operator:
            - and #should be default
          fields:
            - dct:title
            - rdau:publicationStatement
            - @type
            - dct:contributor
            - rdau:noteOnResource
            - dct:bibliographicCitation
            - bibo:isbn13
            - bibo:isbn10
#        nested:
#          path:
#            - dc:contributor
#          query:
#            multi_match:
#              fields:
#                - dc:contributor.foaf:firstName
#                - dc:contributor.foaf:lastName
#              type:
#                - cross_fields #should be default
#              operator:
#                - and # should be default

Person:
  UsedTypes:
    - person
  UsedIndex:
    - testsb
  query:
    multi_match:
      fields:
        - foaf:name
        - foaf:firstName
        - foaf:lastName
        - dbp:pseudonym.de
        - dbp:pseudonym.en
        - dbp:pseudonym.fr
        - dbp:pseudonym.it
        - schema:alternateName
        #- rdfs:label
      type:
        - cross_fields #should be default
      operator:
        - or # should be default